import img4 from '../../../assets/FightClub.jpeg';

export interface Episode {
  id: number;
  title: string;
  duration: string;
  date: string;
  image: string;
  year: number;
  starRating: number;
  desc: string; // Added desc field
}

export const topRated: Episode[] = [
  {
    id: 1,
    title: "Ishaani ",
    duration: "32m",
    date: "24 Apr",
    image: img4,
    year: 2023,
    starRating: 4.5,
    desc: "Ishaani faces intense pressure as she navigates personal and professional challenges.",
  },
  {
    id: 2,
    title: "Armaan ",
    duration: "21m",
    date: "24 Apr",
    image: img4,
    year: 2024,
    starRating: 3.8,
    desc: "Tensions rise as Armaan loses his temper with Ruhi in a dramatic confrontation.",
  },
  {
    id: 3,
    title: "The Final Clash",
    duration: "45m",
    date: "23 Apr",
    image: img4,
    year: 2022,
    starRating: 4.2,
    desc: "A high-stakes battle reaches its climax with unexpected twists.",
  },
  {
    id: 4,
    title: "Secrets Unveiled",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2023,
    starRating: 4.0,
    desc: "Hidden truths come to light, changing the course of relationships. changing the course of relationships. changing the course of relationships. changing the course of relationships. changing the course of relationships. changing the course of relationships. changing the course of relationships. changing the course of relationships.",
  },
  {
    id: 5,
    title: "The Final Clash",
    duration: "45m",
    date: "23 Apr",
    image: img4,
    year: 2022,
    starRating: 4.2,
    desc: "A high-stakes battle reaches its climax with unexpected twists.",
  },
  {
    id: 6,
    title: "Secrets Unveiled",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2023,
    starRating: 4.0,
    desc: "Hidden truths come to light, changing the course of relationships.",
  },
  {
    id: 7,
    title: "The Final Clash",
    duration: "45m",
    date: "23 Apr",
    image: img4,
    year: 2022,
    starRating: 4.2,
    desc: "A high-stakes battle reaches its climax with unexpected twists.",
  },
  {
    id: 8,
    title: "Secrets Unveiled",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2023,
    starRating: 4.0,
    desc: "Hidden truths come to light, changing the course of relationships.",
  },
];

export const hollywood: Episode[] = [
  {
    id: 1,
    title: "Ishaani Under Pressure",
    duration: "32m",
    date: "24 Apr",
    image: img4,
    year: 2023,
    starRating: 4.5,
    desc: "Ishaani faces intense pressure as she navigates personal and professional challenges.",
  },
  {
    id: 2,
    title: "Armaan Snaps at Ruhi",
    duration: "21m",
    date: "24 Apr",
    image: img4,
    year: 2024,
    starRating: 3.8,
    desc: "Tensions rise as Armaan loses his temper with Ruhi in a dramatic confrontation.",
  },
  {
    id: 3,
    title: "The Final Clash",
    duration: "45m",
    date: "23 Apr",
    image: img4,
    year: 2022,
    starRating: 4.2,
    desc: "A high-stakes battle reaches its climax with unexpected twists.",
  },
  {
    id: 4,
    title: "Secrets Unveiled",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2023,
    starRating: 4.0,
    desc: "Hidden truths come to light, changing the course of relationships.",
  },
  {
    id: 5,
    title: "Space Odyssey",
    duration: "40m",
    date: "20 Apr",
    image: img4,
    year: 2021,
    starRating: 4.7,
    desc: "An epic journey through the cosmos with breathtaking visuals.",
  },
  {
    id: 6,
    title: "The Hero's Journey",
    duration: "35m",
    date: "21 Apr",
    image: img4,
    year: 2022,
    starRating: 3.5,
    desc: "A young hero embarks on a quest to save his world.",
  },
  {
    id: 7,
    title: "Cyber Heist",
    duration: "30m",
    date: "22 Apr",
    image: img4,
    year: 2023,
    starRating: 4.1,
    desc: "A thrilling cybercrime adventure with high stakes.",
  },
  {
    id: 8,
    title: "Apocalypse Dawn",
    duration: "50m",
    date: "23 Apr",
    image: img4,
    year: 2024,
    starRating: 4.8,
    desc: "Survivors band together in a post-apocalyptic world.",
  },
  {
    id: 9,
    title: "Apocalypse Dawn",
    duration: "50m",
    date: "23 Apr",
    image: img4,
    year: 2024,
    starRating: 4.8,
    desc: "Survivors band together in a post-apocalyptic world.",
  },
];

export const bollywood: Episode[] = [
  {
    id: 9,
    title: "Dil Se Dil Tak",
    duration: "25m",
    date: "24 Apr",
    image: img4,
    year: 2023,
    starRating: 4.3,
    desc: "A heartfelt love story that transcends all obstacles.",
  },
  {
    id: 10,
    title: "Pyaar Ka Safar",
    duration: "22m",
    date: "23 Apr",
    image: img4,
    year: 2022,
    starRating: 3.9,
    desc: "A romantic journey filled with emotional highs and lows.",
  },
  {
    id: 11,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 12,
    title: "Rishtey",
    duration: "30m",
    date: "21 Apr",
    image: img4,
    year: 2023,
    starRating: 4.2,
    desc: "Exploring the complexities of relationships in modern India.",
  },
  {
    id: 13,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 14,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 15,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 16,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 17,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 18,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 19,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 20,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 21,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 22,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 23,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 24,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 25,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 26,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 27,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 28,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 29,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 30,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  {
    id: 31,
    title: "Dhadkan",
    duration: "28m",
    date: "22 Apr",
    image: img4,
    year: 2021,
    starRating: 4.0,
    desc: "A tale of love, sacrifice, and family bonds.",
  },
  
];